check: fix TS syntax error (#673)
Typescript compiler was failing with:

` node_modules/express-validator/check/check.d.ts:69:58 - error TS1005: ';' expected.`

This adds the missing semicolon.